num_agents: 3
agent_ns: kobuki
agent_launchfile: kobuki.launch
world_launchfile: kobuki_simple_world.launch
world_file: simple.world
catkin_ignore:
  kobuki: 
    - kobuki_keyop
    - kobuki_controller_tutorial
    - kobuki_random_walker
    - kobuki_auto_docking
    - kobuki_controller_tutorial
    - kobuki_node
    - kobuki_testsuite
    - kobuki_safety_controller
  kobuki_desktop:
    - kobuki_qtestsuite