num_agents: 3
agent_ns: kobuki
world_launchfile: kobuki_simple_world.launch
world_file: simple.world

roslaunch:
    onetime: null
    roslaunch_per_agent:
        $launch/kobuki.launch:
            model: $NS
            robotID: $ID
            y: $ID
            x: 0

run_scripts:
    onetime: null
    run_scripts_per_agent:
        $scripts/KobukiTfBroadcaster.py:
            - $NS_$ID
catkin_ignore:
    kobuki: 
        - kobuki_keyop
        - kobuki_controller_tutorial
        - kobuki_random_walker
        - kobuki_auto_docking
        - kobuki_controller_tutorial
        - kobuki_node
        - kobuki_testsuite
        - kobuki_safety_controller
    kobuki_desktop:
        - kobuki_qtestsuite